### ISSUE TITLE
TypeError when requiring module on cygwin

### ISSUE THREAD

**Issue by fholzer** [jonschlinkert/window-size#12]
Running `require('prompt-confirm')` on cygwin results in below error.
This seems due to `windowSize()`evaluating to `undefined` on https://github.com/jonschlinkert/window-size/blob/904a789e18d527e11623838d5cd21a81b57d4f71/index.js#L119 on cygwin.
`undefined` is then assigned to `module.exports`, and later on https://github.com/jonschlinkert/window-size/blob/904a789e18d527e11623838d5cd21a81b57d4f71/index.js#L125 the error is thrown because it can't assign a property to `undefined`.

````
$node index.js
C:\Users\fholzer\Documents\git\prompt-test\node_modules\define-property\index.js:14
    throw new TypeError('expected an object or function.');
    ^

TypeError: expected an object or function.
    at defineProperty (C:\Users\fholzer\Documents\git\prompt-test\node_modules\define-property\index.js:14:11)
    at Object.<anonymous> (C:\Users\fholzer\Documents\git\prompt-test\node_modules\window-size\index.js:125:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\fholzer\Documents\git\prompt-test\node_modules\readline-utils\index.js:10:12)
````

There's two ways of starting a cygwin terminal.
1. via the "Cygwin64 Terminal" shortcut in the start menu. When starting cygwin this way, the error occurs.
2. via `<path-to-cygwin-installation>\cygwin.bat`. When starting cygwin this way, the error doesn't occur.

I'm not sure what makes the difference, but I feel that the more user-friendly way of running cygwin - using the start menu - should work.

**Comment by doowb** [comment]
@fholzer I just published `window-size@1.1.0`. This should fix the loading issue. I'm going to close this, but if you're still having the same issue, please feel free to re-open this issue. If you run into a new problem, please open a new issue.
